config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :recipes do
    collection do
      get :search
    end
  end

  resources :users, only: [:show]
  # get 'users/:id' => 'users#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates_presence_of :avatar
  validates_integrity_of :avatar
  validates_processing_of :avatar

  has_many :recipes

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password,
      :password_confirmation, :remember_me, :avatar, :avatar_cache, :remove_avatar) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password,
      :password_confirmation, :current_password, :avatar, :avatar_cache, :remove_avatar) }
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

# GET displays all the recipes
  def index
    @recipes = Recipe.all
  end

# GET displaying just the selected recipe you want not all of them
  def show
    @recipe = Recipe.find(params[:id])
  end

# GET form for new recipe but DOES NOT save it to the db
  def new
    @recipe = Recipe.new
  end

# GETS form for editing recipe but DOES NOT save it to the db
  def edit
    @recipe = Recipe.find(params[:id])
  end

# POSTS the form to the model to save to the db
  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

# PATCHES information based off your edit form and saves it to the db
  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

# DELETE from db
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  def search
      @recipes = Recipe.where("name LIKE ?", "%#{params[:search]}")

  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :instructions)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #users_controller.rb
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag("logo.png") %>
    <% end %>

    <%= form_tag search_recipes_path, method: :get do %>
    <%= text_field_tag :search %>
    <%= submit_tag "Search" %>
    <% end %>

  <% if user_signed_in? %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "See all Recipes", recipes_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "New Recipe", new_recipe_path, class: "navbar-wagon-item navbar-wagon-link"%>
    <%= link_to "Profile", current_user, class: "navbar-wagon-item navbar-wagon-link"%>

    <a href="" class="navbar-wagon-item navbar-wagon-link"></a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        </ul>
      </div>
    </div>
  </div>
  <% end %>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Recipes</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Log Out</a></li>
      </ul>
    </div>
  </div>
</div>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>


</html>

app/views/recipes/edit.html.erb
<h1>This view will edit the recipe</h1>

<%= form_for @recipe do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :instructions, size: "60x12" %>
  <%= f.submit "Sumbit Edits" %>

<% end %>

app/views/recipes/index.html.erb
<h1>This will index and display the recipes for all users</h1>

<% @recipes.each do |recipe| %>
    <h1><%= recipe.name %></h1>
    <h1><%= recipe.instructions %></h1>
<% end %>

app/views/recipes/new.html.erb
<h1>This is the view for new recipes. It will have a form to input and Post a new recipe to the DB</h1>

<%= form_for @recipe do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :instructions, size: "60x12" %>
  <%= f.submit "Sumbit" %>

<% end %>

app/views/recipes/search.html.erb
<% @recipes.each do |recipe| %>
    <h1><%= recipe.name %></h1>
    <h1><%= recipe.instructions %></h1>
      <%= link_to 'Edit Recipe', edit_recipe_path(recipe) %>
<% end %>

app/views/recipes/show.html.erb
<h1>This view will show 1 recipe</h1>

<h1><%= @recipe.name %></h1>

<h1><%= @recipe.instructions %></h1>

app/views/static_pages/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/berlin');">
  <div class="banner-content">
    <h1>KitchenPal</h1>
    <p>Keep all your recipes organized with KitchenPal</p>
    <a class="btn btn-primary btn-lg">Start now</a>
  </div>
</div>

<!-- Lewagon Cards -->
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <a class="card-link" href="#" ></a>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Le Wagon Copenhagen</h2>
          <p>Very cool city, the best</p>
        </div>
        <a class="card-link" href="#"></a>
      </div>
      <!-- insert <div class="card"> -->
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card>
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Le Wagon Lisbon</h2>
          <p>Very cool city, the best</p>
        </div>
        <a class="card-link" href="#"></a>
      </div>
      <!-- insert <div class="card"> -->
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card>
       <div class="card-category">Popular</div>
       <div class="card-description">
         <h2>Le Wagon Sao Paulo</h2>
         <p>Very cool city, the best</p>
       </div>
       <a class="card-link" href="#"></a>
     </div>
      <!-- insert <div class="card"> -->
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.email %>